import random
import time

number = 40

tt = [
['возникнуть', 'arise', 'arose', 'arisen',],
['проснуться', 'awake', 'awoke', 'awoken',],
['быть', 'be', 'was/were', 'been',],
['бить', 'beat', 'beat', 'beaten',],
['стать', 'become', 'became', 'become',],
['начать', 'begin', 'began', 'begun',],
['сгибать', 'bend', 'bent', 'bent',],
['делать ставку', 'bet', 'bet', 'bet',],
['связывать', 'bind', 'bound', 'bound',],
['кусать', 'bite', 'bit', 'bitten',],
['истекать кровью', 'bleed', 'bled', 'bled',],
['дуть', 'blow', 'blew', 'blown',],
['ломать', 'break', 'broke', 'broken',],
['размножать.разводить', 'breed', 'bred', 'bred',],
['приносить', 'bring', 'brought', 'brought',],
['транслировать', 'broadcast', 'broadcast', 'broadcast',],
['строить', 'build', 'built', 'built',],
['гореть', 'burn', 'burnt/burned', 'burnt/burned',],
['бурстить', 'burst', 'burst', 'burst',],
['покупать', 'buy', 'bought', 'bought',],
['могу', 'can', 'could', '… (been able)',],
['ловить', 'catch', 'caught', 'caught',],
['выбирать', 'choose', 'chose', 'chosen',],
['цепляться', 'cling', 'clung', 'clung',],
['приходить', 'come', 'came', 'come',],
['стоить', 'cost', 'cost', 'cost',],
['ползти', 'creep', 'crept', 'crept',],
['резать', 'cut', 'cut', 'cut',],
['иметь дело', 'deal', 'dealt', 'dealt',],
['копать', 'dig', 'dug', 'dug',],
['делать', 'do', 'did', 'done',],
['рисовать', 'draw', 'drew', 'drawn',],
['мечтать', 'dream', 'dreamt/dreamed', 'dreamt/dreamed',],
['пить', 'drink', 'drank', 'drunk',],
['вести машину', 'drive', 'drove', 'driven',],
['есть', 'eat', 'ate', 'eaten',],
['падать', 'fall', 'fell', 'fallen',],
['кормить', 'feed', 'fed', 'fed',],
['чувствовать', 'feel', 'felt', 'felt',],
['драться', 'fight', 'fought', 'fought',],
['искать', 'find', 'found', 'found',],
['летать', 'fly', 'flew', 'flown',],
['запрещать', 'forbid', 'forbade', 'forbidden',],
['забывать', 'forget', 'forgot', 'forgotten',],
['прощать', 'forgive', 'forgave', 'forgiven',],
['замерзать', 'freeze', 'froze', 'frozen',],
['получать', 'get', 'got', 'got',],
['давать', 'give', 'gave', 'given',],
['идти', 'go', 'went', 'gone',],
['молоть', 'grind', 'ground', 'ground',],
['расти', 'grow', 'grew', 'grown',],
['висеть', 'hang', 'hung', 'hung',],
['иметь', 'have', 'had', 'had',],
['слышать', 'hear', 'heard', 'heard',],
['прятаться', 'hide', 'hid', 'hidden',],
['бить', 'hit', 'hit', 'hit',],
['держать', 'hold', 'held', 'held',],
['болеть', 'hurt', 'hurt', 'hurt',],
['держать', 'keep', 'kept', 'kept',],
['преклоняться', 'kneel', 'knelt', 'knelt',],
['знать', 'know', 'knew', 'known',],
['класть', 'lay', 'laid', 'laid',],
['вести', 'lead', 'led', 'led',],
['опираться', 'lean', 'leant/leaned', 'leant/leaned',],
['учить', 'learn', 'learnt/learned', 'learnt/learned',],
['оставлять, покидать', 'leave', 'left', 'left',],
['давать в долг', 'lend', 'lent', 'lent',],
['лежать', 'lie', 'lay', 'lain',],
['врать', 'lie', 'lied', 'lied',],
['зажигать', 'light', 'lit/lighted', 'lit/lighted',],
['терять', 'lose', 'lost', 'lost',],
['делать', 'make', 'made', 'made',],
['мочь', 'may', 'might', '…',],
['иметь в виду', 'mean', 'meant', 'meant',],
['встречать', 'meet', 'met', 'met',],
['косить', 'mow', 'mowed', 'mown/mowed',],
['платить', 'pay', 'paid', 'paid',],
['класть', 'put', 'put', 'put',],
['читать', 'read', 'read', 'read',],
['скакать', 'ride', 'rode', 'ridden',],
['звонить', 'ring', 'rang', 'rung',],
['подниматься, восходить', 'rise', 'rose', 'risen',],
['бежать', 'run', 'ran', 'run',],
['пилить', 'saw', 'sawed', 'sawn/sawed',],
['говорить', 'say', 'said', 'said',],
['видеть', 'see', 'saw', 'seen',],
['продавать', 'sell', 'sold', 'sold',],
['отправлять', 'send', 'sent', 'sent',],
['настраивать устанавливать', 'set', 'set', 'set',],
['шить', 'sew', 'sewed', 'sewn/sewed',],
['трясти', 'shake', 'shook', 'shaken',],
['пролить', 'shed', 'shed', 'shed',],
['светить сиять', 'shine', 'shone', 'shone',],
['стрелять', 'shoot', 'shot', 'shot',],
['показывать', 'show', 'showed', 'shown',],
['сокращаться, сжиматься', 'shrink', 'shrank', 'shrunk',],
['закрыть, захлопнуть', 'shut', 'shut', 'shut',],
['петь', 'sing', 'sang', 'sung',],
['топить тонуть', 'sink', 'sank', 'sunk',],
['сидеть', 'sit', 'sat', 'sat',],
['спать', 'sleep', 'slept', 'slept',],
['скользить', 'slide', 'slid', 'slid',],
['пахнуть', 'smell', 'smelt', 'smelt',],
['сеять', 'sow', 'sowed', 'sown/sowed',],
['говорить', 'speak', 'spoke', 'spoken',],
['произносить по буквам', 'spell', 'spelt/spelled', 'spelt/spelled',],
['тратить', 'spend', 'spent', 'spent',],
['пролить', 'spill', 'spilt/spilled', 'spilt/spilled',],
['плюнуть', 'spit', 'spat', 'spat',],
['распостранять', 'spread', 'spread', 'spread',],
['стоять', 'stand', 'stood', 'stood',],
['воровать', 'steal', 'stole', 'stolen',],
['держаться', 'stick', 'stuck', 'stuck',],
['жалить', 'sting', 'stung', 'stung',],
['вонять', 'stink', 'stank', 'stunk',],
['бить, бастовать', 'strike', 'struck', 'struck',],
['клясться ругаться', 'swear', 'swore', 'sworn',],
['подметать', 'sweep', 'swept', 'swept',],
['набухать', 'swell', 'swelled', 'swollen/swelled',],
['плыть', 'swim', 'swam', 'swum',],
['качаться', 'swing', 'swung', 'swung',],
['брать', 'take', 'took', 'taken',],
['учить', 'teach', 'taught', 'taught',],
['рвать', 'tear', 'tore', 'torn',],
['сказать', 'tell', 'told', 'told',],
['думать', 'think', 'thought', 'thought',],
['бросать', 'throw', 'threw', 'thrown',],
['понимать', 'understand', 'understood', 'understood',],
['будить, просыпаться', 'wake', 'woke', 'woken',],
['носить одежду', 'wear', 'wore', 'worn',],
['плакать', 'weep', 'wept', 'wept',],
['выигрывать', 'win', 'won', 'won',],
['писать', 'write', 'wrote', 'written',],
]

#number = int(sys.argv[1]) if len(sys.argv)>1 else len(tt)
train_words = tt[:number]

while train_words:
    print(len(train_words))
    word = train_words[random.randint(0, len(train_words) - 1)]
    train_words.remove(word)
    input(word[0])
    input(word[1])
    print(f'{word[2]} {word[3]}')
    print('\n')
    time.sleep(1)
